name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
        working-directory: app

      - name: Run tests
        run: npm test
        working-directory: app

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        env:
          ECR_REPO: <ECR_REPO_URL>
        run: |
          docker build -t $ECR_REPO:hola-app app
          docker push $ECR_REPO:hola-app

      - name: Install kubectl
        run: |
          curl -LO https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name hola-cluster --region us-east-1

      - name: Install Kustomize
        run: |
          curl -s \"https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh\" | bash
          sudo mv kustomize /usr/local/bin/

      - name: Deploy to EKS with Kustomize
        run: |
          cd k8s/overlays/dev
          kustomize edit set image placeholder-image=<ECR_REPO_URL>:hola-app
          kustomize build . | kubectl apply -f -
