name: Build
on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Java
        working-directory: app
        run: docker build -t desafio-app -f app/Dockerfile app/
        
