name: Pipeline despliegue

on:
  push:
    branches: [main]

jobs:
  build-test:
    uses: ./.github/workflows/template-build-test.yaml

  docker:
    needs: build-test
    uses: ./.github/workflows/template-build-image.yaml
    with:
      image_name: ${{ needs.build-test.outputs.image_name }}
    
  kustomize:
    needs: docker
    uses: ./.github/workflows/template-kustomization.yaml

  deploy:
    needs: kustomize
    uses: ./.github/workflows/template-deploy.yaml
    secrets:
      TEST_S: ${{ secrets.TEST_S }}
    with:
      TEST: ${{ vars.TEST }}    