# .github/workflows/ci-cd.yaml
name: Main Pipeline

on:
  push:
    branches: [main]

jobs:
  generate:
    uses: ./.github/workflows/template-output.yaml

  consume:
    needs: generate
    uses: ./.github/workflows/template-use-output.yaml
    with:
      test_value: ${{ needs.generate.outputs.test_value }}
