name: Main pipeline

on:
  push:
    branches: [main]

jobs:
  build-test:
    uses: ./.github/workflows/template-build-test.yaml

  docker:
    needs: build-test
    uses: ./.github/workflows/template-build-image.yaml
    with:
      image_name: ${{ needs.build-test.outputs.image_name }}
