name: Main Pipeline

on:
  push:
    branches: [main]

jobs:
  generate:
    uses: ./.github/workflows/template-build-test.yaml

  consume:
    needs: generate
    uses: ./.github/workflows/template-build-image.yaml
    with:
      test_value: ${{ needs.generate.outputs.test_value }}
