name: Main pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yaml
    secrets:
      TEST_S: ${{ secrets.TEST_S }}
    with:
      TEST: ${{ vars.TEST }}
