name: Template - Docker

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Descargar artifact
        uses: actions/download-artifact@v4
        with:
          name: app-build
          path: app/

      - name: Verificar nombre de imagen
        run: echo "Nombre recibido -> ${{ inputs.image_name }}"

      - name: Build imagen Docker
        run: docker build -t ${{ inputs.image_name }}:latest -f app/Dockerfile app/

      - name: Mostrar tamaño de la imagen Docker
        run: |
          IMAGE_ID=$(docker images -q ${{ inputs.image_name }}:latest)
          IMAGE_SIZE=$(docker image inspect $IMAGE_ID --format='{{.Size}}')
          echo "Tamaño de la imagen: $((IMAGE_SIZE / 1000000)) MB"