# .github/workflows/template-use-output.yaml
name: Output Consumer

on:
  workflow_call:
    inputs:
      test_value:
        required: true
        type: string

jobs:
  print:
    runs-on: ubuntu-latest

    steps:
      - name: Imprimir valor recibido
        run: echo "Recibido: ${{ inputs.test_value }}"
