name: Template - Docker

on: workflow_call

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-build
          path: app/

      - name: Show build files
        run: ls -R app

      - name: Obtener nombre desde package.json
        run: |
          echo "IMAGE_NAME=$(jq -r .name app/package.json)" >> $GITHUB_ENV

      - name: Mostrar nombre de la imagen
        run: echo "Nombre de la imagen $IMAGE_NAME"

      - name: Test
        run: jq -r .name app/package.json

      - name: Build imagen docker
        run: docker build -t $IMAGE_NAME:latest -f app/Dockerfile app/