name: Template - Docker

on: workflow_call

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-build
          path: app/

      - name: Show build files
        run: ls -R app

      - name: Obtener nombre desde package.json
        id: imagen
        run: |
          echo "IMAGE_NAME=$(jq -r .name app/package.json)" >> $GITHUB_ENV
          echo $IMAGE_NAME

      - name: Build imagen docker
        run: docker build -t desafio-app:latest -f app/Dockerfile app/
