name: Template - Docker

on: workflow_call

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-build
          path: app/

      - name: Show build files
        run: ls -R app

      - name: Build imagen docker
        run: docker build -t desafio-app:latest -f app/Dockerfile app/
