name: Template - Build & Test

on: workflow_call

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: app
        run: npm install
        
      - name: Unit tests
        working-directory: app
        run: npm test

      - name: Lint
        working-directory: app
        run: npx eslint src/
            
      - name: Directory for artifact
        run: mkdir -p build && cp -R app/* build/

      - name: Upload compiled artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: build/
